### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by veelupu** [aarohakkinen/KeyboardTrainer#1]
**Tiedosto ladattu 28.4.2020 kello 11.41**

Ohjelman koodi on selkeää ja luettavaa. Luokkajako on selkeä ja nimentä kurssin ohjeiden mukaista. Jokaisella luokalla on oma, selkeä ja rajattu vastuualueensa. Luokkien metodit ovat selkeitä ja lyhyitä sekä nimetty oikein. Pakkausten osalta DAO-mallia ja nimentäohjeita on noudatettu; pakkausjako on selkeä. Ainoastaan kurssin laatuvaatimuksissa mainittua juuripakkausta ei ole.

**Virheiden** (SQLException) **käsittelystä**: Kurssin laatuvaatimusten mukaan ohjelma ei saisi tulostaa virheitä komentoriville. Näin kuitenkin tapahtuu Service-luokan addToHistory()-metodissa. Lisäksi jäin pohtimaan, missä KeyboardTrainerUI-luokan init()-metodin heittämä poikkeus käsitellään (vai käsitelläänkö sitä).

**Accuracy:** Testasin peliä pelaamalla kymmenkunta kierrosta. Jostain syystä ensimmäisellä pelikierroksella ohjelma ei ottanut tekemiäni virheitä lainkaan huomioon vaan väitti virheettömyyden olevan 100%. Myöhemmillä kierroksilla prosenttiluku oli oikein vaihtelevasti: välillä oikein ja välillä vähemmän kuin 100%, vaikka virhenäpppäilyjä ei ollut. 

**Tilasto-välilehdellä** olevan ”Correct keys” -sarakkeen sisältöä en aivan ymmärtänyt. Mitä sen on tarkoitus kuvata? Siinä olevat luvut muuttuivat menneiden pelien osalta, kun pelasin peliä eteenpäin. Kuvittelin aluksi, että siinä pitäisi olla sama luku kuin pelin päättyessä kerrottu oikein saatujen merkkien määrä, mutta näin ei ollut (ero oli aluksi noin kaksinkertainen ja kasvoi, kun peliä pelasi lisää). Mikäli sarakkeen luvut ovat kuten tarkoitettu, kenties sarakkeen nimentää voisi muuttaa kuvaavammaksi?

Ylipäätään tilasto-välilehti oli kiva ja hyödyllinen! Jos jotain haluaa vielä lisätä, ehkä jokin viivadiagrammi kuvaamaan omaa kehitystään voisi olla kiva. Ylipäätään peli oli hauska ja hyödyllinen – näkisin tällä hyvinkin käyttöä peruskoulussa kun oppilaat harjoittelevat tietokoneen käyttöä. Erityisesti jos sitä laajentaisi vaikka eri tasoille: yhdellä voisi harjoitella ihan isoja ja pieniä kirjaimia, toisella numeroita, kolmannella erikoismerkkejä… Hieno sovellus kaikkiaan!

**Comment by aarohakkinen** [comment]
Kiitos kattavasta ja hyödyllisestä palautteesta! Tosiaan peliin oli päätynyt viime päivitysten yhteydessä virhe, joka oli jäänyt itseltäni huomaamatta. Tunnin etsimisen jälkeen huomasin, että `getGames()` lisää `Keystroke` oliot joka suorituskerralla uudelleen `Game` olioon. Tämä johti mainitsemaasi epäloogiseen käyttäytymiseen.

Virheiden käsittelyn olin ajatellut toimivan siten, että tietokantavirheen tapauksessa ilmoitus tulisi komentoriville. Toisaalta käyttäjän olisi helpompi reagoida virheeseen, mikäli se näkyisi graafisella käyttöliittymällä. Pelin ilmoittama tarkkuus ei ota huomioon vääriä merkkejä, jotka on poistettu ennen oikean merkin kirjoittamista. Ymmärrettävästi tämä voi aiheuttaa hämmennystä. Pitää katsoa miten siitä saisi selkeämmän.

Laajennus eri merkeille on toteutuskelpoinen idea. Lisäksi ilman sitä asetusnäkymä jäisi melko tyhjäksi. Mikäli aika riittää, merkkien valinta asetuksista saattaa hyvinkin päätyä viimeisen viikon palautukseen.
